spring.application.name=CubeGridLab
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/CubeGridLab
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JWT Configuration
app.jwtSecret=${JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidationPleaseChangeIt12345678}
app.jwtExpirationMs=86400000

